## GAWD dataset

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/pavt/GHAW-H/blob/main/notebooks/load_GAWD.ipynb)

This notebook loads **A Dataset of GitHub Agentic Workflow Histories: Early Adopters** in the same lightweight style as `load_AIDev.ipynb`.

By default this notebook reads the public Parquet files from Hugging Face, matching how an external user would load the dataset. For local development, set `USE_LOCAL_MIRROR = True` to use a release folder with the same `data/*.parquet` layout.

In [1]:
from __future__ import annotations

import importlib.util
import subprocess
import sys
from io import BytesIO
from pathlib import Path
from urllib.request import urlopen

REQUIRED_PACKAGES = {
    "pandas": "pandas",
    "pyarrow": "pyarrow",
}

if "google.colab" in sys.modules:
    missing = [
        package
        for package, import_name in REQUIRED_PACKAGES.items()
        if importlib.util.find_spec(import_name) is None
    ]
    if missing:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])

import pandas as pd

DATASET_ID = "pavtch/GHAW-H"
DATASET_REVISION = "main"
LOCAL_RELEASE_CANDIDATES = [
    Path(".."),
    Path("."),
    Path("../releases/gh-aw-early-adopters-source-history-2026-06-26"),
    Path("releases/gh-aw-early-adopters-source-history-2026-06-26"),
    Path("../releases/gawd"),
    Path("releases/gawd"),
]
LOCAL_RELEASE_MIRROR = next(
    (
        path.resolve()
        for path in LOCAL_RELEASE_CANDIDATES
        if (path / "data").is_dir() and any((path / "data").glob("*.parquet"))
    ),
    None,
)
USE_LOCAL_MIRROR = "google.colab" not in sys.modules and LOCAL_RELEASE_MIRROR is not None


def remote_parquet_url(table_name: str) -> str:
    return (
        f"https://huggingface.co/datasets/{DATASET_ID}/resolve/"
        f"{DATASET_REVISION}/data/{table_name}.parquet"
    )


def local_parquet_path(table_name: str) -> Path:
    if LOCAL_RELEASE_MIRROR is None:
        raise FileNotFoundError("No local release mirror with a data/ directory was found.")
    return LOCAL_RELEASE_MIRROR / "data" / f"{table_name}.parquet"


def parquet_path(table_name: str) -> str:
    if USE_LOCAL_MIRROR:
        return str(local_parquet_path(table_name))
    return remote_parquet_url(table_name)


def read_parquet_table(table_name: str) -> pd.DataFrame:
    if USE_LOCAL_MIRROR:
        return pd.read_parquet(local_parquet_path(table_name))

    try:
        with urlopen(remote_parquet_url(table_name)) as response:
            return pd.read_parquet(BytesIO(response.read()))
    except Exception:
        if LOCAL_RELEASE_MIRROR is not None:
            return pd.read_parquet(local_parquet_path(table_name))
        raise

NOTEBOOK_DIR = Path("data_analysis") if Path("data_analysis").is_dir() else Path(".")

In [2]:
repository_df = read_parquet_table("repository")
source_markdown_file_history_df = read_parquet_table("source_markdown_file_history")
source_markdown_file_snapshot_df = read_parquet_table("source_markdown_file_snapshot")
source_markdown_file_version_df = read_parquet_table("source_markdown_file_version")
lock_file_snapshot_df = read_parquet_table("lock_file_snapshot")

In [3]:
repository_df

           repository_id  ...             pushed_at
0    9089213639968762207  ...  2026-06-26T18:15:59Z
1    4902717555605226939  ...  2026-06-14T06:40:46Z
2    8401317167309685863  ...  2026-06-26T15:41:28Z
3    1689116779471759733  ...  2026-06-27T12:44:15Z
4    8707166185860304590  ...  2026-06-27T19:40:28Z
..                   ...  ...                   ...
257  5427182896104728152  ...  2026-06-26T16:25:52Z
258  8936047867513918691  ...  2026-06-27T11:22:27Z
259  3451869941153973759  ...  2026-06-22T05:17:06Z
260  3591656885695211674  ...  2026-06-25T08:50:13Z
261  6077468482482437617  ...  2026-06-26T03:10:53Z

[262 rows x 12 columns]

In [4]:
source_markdown_file_history_df

     source_markdown_file_history_id  version_count
0                                  1              1
1                                  2              4
2                                  3              3
3                                  4              2
4                                  5              3
..                               ...            ...
599                              600              1
600                              601              1
601                              602              1
602                              603              1
603                              604              2

[604 rows x 2 columns]

In [5]:
source_markdown_file_snapshot_df

      source_markdown_file_snapshot_id  ...                                               body
0                                    1  ...  \n# Daily Issue Triage\n\n<!-- Note - this fil...
1                                    2  ...  \n# Daily Repo Status\n\nCreate an upbeat dail...
2                                    3  ...  \n# Daily Repo Status\n\nCreate an upbeat dail...
3                                    4  ...  \n# Repo Status\n\nCreate an upbeat daily stat...
4                                    5  ...  \n# Repo Status\n\nCreate an upbeat daily stat...
...                                ...  ...                                                ...
2815                              2816  ...  \n# pr-prior-art-reviewer\n\nYou are pr-prior-...
2816                              2817  ...  \n# pr-security-reviewer\n\nYou are pr-securit...
2817                              2818  ...  \n# pr-testing-reviewer\n\nYou are pr-testing-...
2818                              2819  ...  \n# YAML Snippet Validator\n\nYou are an AI ag...
2819                              2820  ...  \n# YAML Snippet Validator\n\nYou are an AI ag...

[2820 rows x 6 columns]

In [6]:
source_markdown_file_version_df

      source_markdown_file_version_id  ...  successor_source_markdown_file_version_id
0                                   1  ...                                        NaN
1                                   2  ...                                        3.0
2                                   3  ...                                        4.0
3                                   4  ...                                        5.0
4                                   5  ...                                        NaN
...                               ...  ...                                        ...
2815                             2816  ...                                        NaN
2816                             2817  ...                                        NaN
2817                             2818  ...                                        NaN
2818                             2819  ...                                     2820.0
2819                             2820  ...                                        NaN

[2820 rows x 8 columns]

In [7]:
lock_file_snapshot_df

      lock_file_snapshot_id  ...                                  file_sha
0                         1  ...  bd7db9978d40bfd8799dc53087f916a9ac5691a8
1                         2  ...  36847a060a10d0e585b1abffbd6e4e3eea3a3ba9
2                         3  ...  1d7e7eecd14dee89841a371b7d85ea5dd9032e19
3                         4  ...  7c3d20a166ea1080045dfd7a99e3d638900f5fa0
4                         5  ...  98d26f1d559e5ccb0f3719d863a084d24777d877
...                     ...  ...                                       ...
2815                   2816  ...  0430f792a7c0f2320b8010545494e21f3f9606f5
2816                   2817  ...  b8b99b6daf80020c24f983e47afb95f8cc3b0399
2817                   2818  ...  c15f52d374d27bba37ff9a49f9656de46ae50894
2818                   2819  ...  fc6242d38079d9928724d3de9257a6f9aed58df7
2819                   2820  ...  8c38a8418991f633fa17befa06ae39b749c2ea89

[2820 rows x 5 columns]

## Table sizes

In [8]:
table_sizes = pd.DataFrame(
    [
        {"table": "repository", "rows": len(repository_df)},
        {
            "table": "source_markdown_file_history",
            "rows": len(source_markdown_file_history_df),
        },
        {
            "table": "source_markdown_file_snapshot",
            "rows": len(source_markdown_file_snapshot_df),
        },
        {
            "table": "source_markdown_file_version",
            "rows": len(source_markdown_file_version_df),
        },
        {"table": "lock_file_snapshot", "rows": len(lock_file_snapshot_df)},
    ]
)
table_sizes

                           table  rows
0                     repository   262
1   source_markdown_file_history   604
2  source_markdown_file_snapshot  2820
3   source_markdown_file_version  2820
4             lock_file_snapshot  2820

## Join source versions with repositories

This dataset does not have pull requests or users like AIDev. The central history view links repositories, observed source Markdown snapshots, and source Markdown versions.

In [9]:
source_version_repo_df = (
    source_markdown_file_version_df.merge(
        source_markdown_file_snapshot_df,
        on="source_markdown_file_snapshot_id",
        how="inner",
        validate="many_to_one",
    )
    .merge(
        repository_df,
        on="repository_id",
        how="left",
        validate="many_to_one",
    )
)

source_version_repo_df

      source_markdown_file_version_id  ...             pushed_at
0                                   1  ...  2026-06-26T18:15:59Z
1                                   2  ...  2026-06-26T18:15:59Z
2                                   3  ...  2026-06-26T18:15:59Z
3                                   4  ...  2026-06-26T18:15:59Z
4                                   5  ...  2026-06-26T18:15:59Z
...                               ...  ...                   ...
2815                             2816  ...  2026-06-26T03:10:53Z
2816                             2817  ...  2026-06-26T03:10:53Z
2817                             2818  ...  2026-06-26T03:10:53Z
2818                             2819  ...  2026-06-26T03:10:53Z
2819                             2820  ...  2026-06-26T03:10:53Z

[2820 rows x 24 columns]

## Observed adoption by repository

A repository's observed adoption date is the earliest `committed_at` timestamp among its published GH-AW source Markdown versions.

In [10]:
source_version_repo_df["committed_at"] = pd.to_datetime(
    source_version_repo_df["committed_at"],
    utc=True,
    errors="coerce",
)

observed_adoption_df = (
    source_version_repo_df.dropna(subset=["committed_at"])
    .sort_values(["repository_id", "committed_at", "rank"])
    .groupby("repository_id", as_index=False)
    .agg(
        repo_full_name=("repo_full_name", "first"),
        main_language=("main_language", "first"),
        license=("license", "first"),
        stars=("stars", "first"),
        forks=("forks", "first"),
        first_observed_at=("committed_at", "first"),
        first_source_path=("path", "first"),
        observed_versions=("source_markdown_file_version_id", "count"),
        observed_source_paths=("path", "nunique"),
    )
    .sort_values("first_observed_at")
)

observed_adoption_df

           repository_id  ... observed_source_paths
211  7640649877921565393  ...                     8
23    892592735414390340  ...                     5
198  7061224288023129471  ...                     2
97   3532360678775308556  ...                     1
163  6001044222039231227  ...                     5
..                   ...  ...                   ...
103  3721005143461110050  ...                     1
154  5423802872524571249  ...                     1
232  8401317167309685863  ...                     1
28   1084606090191205130  ...                     1
99   3591656885695211674  ...                     1

[262 rows x 10 columns]

## Monthly cumulative adoption

In [11]:
monthly_adoption_df = (
    observed_adoption_df.assign(
        adoption_month=lambda df: df["first_observed_at"]
        .dt.tz_convert(None)
        .dt.to_period("M")
        .dt.to_timestamp()
    )
    .groupby("adoption_month", as_index=False)
    .agg(new_repositories=("repository_id", "count"))
    .sort_values("adoption_month")
)
monthly_adoption_df["cumulative_repositories"] = monthly_adoption_df[
    "new_repositories"
].cumsum()

monthly_adoption_df

  adoption_month  new_repositories  cumulative_repositories
0     2025-10-01                 4                        4
1     2025-11-01                 1                        5
2     2025-12-01                 3                        8
3     2026-01-01                 6                       14
4     2026-02-01                67                       81
5     2026-03-01                62                      143
6     2026-04-01                35                      178
7     2026-05-01                75                      253
8     2026-06-01                 9                      262